//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner
    {
        public int owner_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> car_id { get; set; }
    
        public virtual car car { get; set; }
    }
}
